version: '3'
services:
  tmodloader:
    image: 'sithy/tmodloader1.4:latest'
    container_name: 'tmodloader'
    pull_policy: always
    user: terraria:terraria
    working_dir: /home/terraria/terraria-server
    ports:
      - "7777:7777"
    expose:
      - "7777"
    environment:
      # Enable the Calamity mod and CalamityMusic mod.
      - "TMOD_ENABLEDMODS="Mod1","Mod2""
      # Shutdown Message and Autosave Interval (In Minutes)
      - "TMOD_SHUTDOWN_MESSAGE=Goodbye!"
      - "TMOD_AUTOSAVE_INTERVAL=15"
      # Server Settings
      - "TMOD_MOTD=Welcome to my tModLoader Server!"
      - "TMOD_PASS=secret"
      - "TMOD_MAXPLAYERS=16"
      # The following world settings are only used when generating a new world.
      - "TMOD_WORLDNAME=Earth"
      - "TMOD_WORLDSIZE=2"
      - "TMOD_WORLDSEED=not the bees!"
      - "TMOD_DIFFICULTY=3"
      # (Deprecated) If TMOD_USECONFIGFILE is set to "Yes", it is expected to have a serverconfig.txt mapped. The Server Settings above will be ignored.
      - "TMOD_USECONFIGFILE=No"
      - "UPDATE_NOTICE=false"

    volumes:
    #### UPDATE THE BELOW PATHS TO A DIRECTORY LOCAL TO YOUR MACHINE #####
      - "path/to/tModLoaderFolder/home/terraria/.local/share/Terraria/tModLoader"
      # Uncomment the below line if you plan to use a mapped config file. 
      # - "/path/to/config/config.txt:/root/terraria-server/serverconfig.txt"
